// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: internal_router.proto

package internalpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InternalRouter_RelayCommand_FullMethodName = "/gnat.internal.InternalRouter/RelayCommand"
	InternalRouter_Ping_FullMethodName         = "/gnat.internal.InternalRouter/Ping"
)

// InternalRouterClient is the client API for InternalRouter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 内部节点间路由服务
type InternalRouterClient interface {
	// 跨节点转发车辆控制指令
	RelayCommand(ctx context.Context, in *RelayRequest, opts ...grpc.CallOption) (*RelayResponse, error)
	// 节点间健康检查（可选，用于连接池的保活机制）
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type internalRouterClient struct {
	cc grpc.ClientConnInterface
}

func NewInternalRouterClient(cc grpc.ClientConnInterface) InternalRouterClient {
	return &internalRouterClient{cc}
}

func (c *internalRouterClient) RelayCommand(ctx context.Context, in *RelayRequest, opts ...grpc.CallOption) (*RelayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RelayResponse)
	err := c.cc.Invoke(ctx, InternalRouter_RelayCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalRouterClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, InternalRouter_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternalRouterServer is the server API for InternalRouter service.
// All implementations should embed UnimplementedInternalRouterServer
// for forward compatibility.
//
// 内部节点间路由服务
type InternalRouterServer interface {
	// 跨节点转发车辆控制指令
	RelayCommand(context.Context, *RelayRequest) (*RelayResponse, error)
	// 节点间健康检查（可选，用于连接池的保活机制）
	Ping(context.Context, *PingRequest) (*PingResponse, error)
}

// UnimplementedInternalRouterServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInternalRouterServer struct{}

func (UnimplementedInternalRouterServer) RelayCommand(context.Context, *RelayRequest) (*RelayResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RelayCommand not implemented")
}
func (UnimplementedInternalRouterServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedInternalRouterServer) testEmbeddedByValue() {}

// UnsafeInternalRouterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InternalRouterServer will
// result in compilation errors.
type UnsafeInternalRouterServer interface {
	mustEmbedUnimplementedInternalRouterServer()
}

func RegisterInternalRouterServer(s grpc.ServiceRegistrar, srv InternalRouterServer) {
	// If the following call panics, it indicates UnimplementedInternalRouterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InternalRouter_ServiceDesc, srv)
}

func _InternalRouter_RelayCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RelayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalRouterServer).RelayCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalRouter_RelayCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalRouterServer).RelayCommand(ctx, req.(*RelayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalRouter_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalRouterServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalRouter_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalRouterServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InternalRouter_ServiceDesc is the grpc.ServiceDesc for InternalRouter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InternalRouter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gnat.internal.InternalRouter",
	HandlerType: (*InternalRouterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RelayCommand",
			Handler:    _InternalRouter_RelayCommand_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _InternalRouter_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal_router.proto",
}
