// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: internal_router.proto

package internalpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 跨节点转发请求
type RelayRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 链路追踪 ID，用于在分布式日志中串联整个指令下发链路
	TraceId string `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// 目标车辆 ID (如 VIN 码)
	DeviceId string `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// 下发的指令数据 (二进制格式，兼容 MQTT/TCP 等协议)
	Payload []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	// 指令下发的超时时间戳 (Unix 毫秒)，防止跨节点转发后指令已过期
	ExpireAt      int64 `protobuf:"varint,4,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayRequest) Reset() {
	*x = RelayRequest{}
	mi := &file_internal_router_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayRequest) ProtoMessage() {}

func (x *RelayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_router_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayRequest.ProtoReflect.Descriptor instead.
func (*RelayRequest) Descriptor() ([]byte, []int) {
	return file_internal_router_proto_rawDescGZIP(), []int{0}
}

func (x *RelayRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *RelayRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *RelayRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RelayRequest) GetExpireAt() int64 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

// 跨节点转发响应
type RelayResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 是否成功下发到车辆
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// 附加信息或错误描述
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// 如果云端需要车辆同步返回数据，可在此字段中携带回传内容
	ResponseData  []byte `protobuf:"bytes,3,opt,name=response_data,json=responseData,proto3" json:"response_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayResponse) Reset() {
	*x = RelayResponse{}
	mi := &file_internal_router_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayResponse) ProtoMessage() {}

func (x *RelayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_router_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayResponse.ProtoReflect.Descriptor instead.
func (*RelayResponse) Descriptor() ([]byte, []int) {
	return file_internal_router_proto_rawDescGZIP(), []int{1}
}

func (x *RelayResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RelayResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RelayResponse) GetResponseData() []byte {
	if x != nil {
		return x.ResponseData
	}
	return nil
}

// 健康检查请求
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeIp        string                 `protobuf:"bytes,1,opt,name=node_ip,json=nodeIp,proto3" json:"node_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_internal_router_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_router_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_internal_router_proto_rawDescGZIP(), []int{2}
}

func (x *PingRequest) GetNodeIp() string {
	if x != nil {
		return x.NodeIp
	}
	return ""
}

// 健康检查响应
type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_internal_router_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_router_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_internal_router_proto_rawDescGZIP(), []int{3}
}

func (x *PingResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_internal_router_proto protoreflect.FileDescriptor

const file_internal_router_proto_rawDesc = "" +
	"\n" +
	"\x15internal_router.proto\x12\rgnat.internal\"}\n" +
	"\fRelayRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1b\n" +
	"\texpire_at\x18\x04 \x01(\x03R\bexpireAt\"h\n" +
	"\rRelayResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rresponse_data\x18\x03 \x01(\fR\fresponseData\"&\n" +
	"\vPingRequest\x12\x17\n" +
	"\anode_ip\x18\x01 \x01(\tR\x06nodeIp\",\n" +
	"\fPingResponse\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp2\x9c\x01\n" +
	"\x0eInternalRouter\x12I\n" +
	"\fRelayCommand\x12\x1b.gnat.internal.RelayRequest\x1a\x1c.gnat.internal.RelayResponse\x12?\n" +
	"\x04Ping\x12\x1a.gnat.internal.PingRequest\x1a\x1b.gnat.internal.PingResponseB\x0eZ\f./internalpbb\x06proto3"

var (
	file_internal_router_proto_rawDescOnce sync.Once
	file_internal_router_proto_rawDescData []byte
)

func file_internal_router_proto_rawDescGZIP() []byte {
	file_internal_router_proto_rawDescOnce.Do(func() {
		file_internal_router_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_router_proto_rawDesc), len(file_internal_router_proto_rawDesc)))
	})
	return file_internal_router_proto_rawDescData
}

var file_internal_router_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_router_proto_goTypes = []any{
	(*RelayRequest)(nil),  // 0: gnat.internal.RelayRequest
	(*RelayResponse)(nil), // 1: gnat.internal.RelayResponse
	(*PingRequest)(nil),   // 2: gnat.internal.PingRequest
	(*PingResponse)(nil),  // 3: gnat.internal.PingResponse
}
var file_internal_router_proto_depIdxs = []int32{
	0, // 0: gnat.internal.InternalRouter.RelayCommand:input_type -> gnat.internal.RelayRequest
	2, // 1: gnat.internal.InternalRouter.Ping:input_type -> gnat.internal.PingRequest
	1, // 2: gnat.internal.InternalRouter.RelayCommand:output_type -> gnat.internal.RelayResponse
	3, // 3: gnat.internal.InternalRouter.Ping:output_type -> gnat.internal.PingResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_router_proto_init() }
func file_internal_router_proto_init() {
	if File_internal_router_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_router_proto_rawDesc), len(file_internal_router_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_router_proto_goTypes,
		DependencyIndexes: file_internal_router_proto_depIdxs,
		MessageInfos:      file_internal_router_proto_msgTypes,
	}.Build()
	File_internal_router_proto = out.File
	file_internal_router_proto_goTypes = nil
	file_internal_router_proto_depIdxs = nil
}
