// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package engine

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type XdpEngineCmdPacket struct {
	_          structs.HostLayout
	DeviceId   [32]int8
	Payload    [1024]int8
	PayloadLen uint32
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	XdpEngineMapCmdQueue   = "cmd_queue"
	XdpEngineProgXdpEngine = "xdp_engine"
)

// LoadXdpEngine returns the embedded CollectionSpec for XdpEngine.
func LoadXdpEngine() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_XdpEngineBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load XdpEngine: %w", err)
	}

	return spec, err
}

// LoadXdpEngineObjects loads XdpEngine and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*XdpEngineObjects
//	*XdpEnginePrograms
//	*XdpEngineMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadXdpEngineObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadXdpEngine()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// XdpEngineSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type XdpEngineSpecs struct {
	XdpEngineProgramSpecs
	XdpEngineMapSpecs
	XdpEngineVariableSpecs
}

// XdpEngineProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type XdpEngineProgramSpecs struct {
	XdpEngine *ebpf.ProgramSpec `ebpf:"xdp_engine"`
}

// XdpEngineMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type XdpEngineMapSpecs struct {
	CmdQueue *ebpf.MapSpec `ebpf:"cmd_queue"`
}

// XdpEngineVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type XdpEngineVariableSpecs struct {
}

// XdpEngineObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadXdpEngineObjects or ebpf.CollectionSpec.LoadAndAssign.
type XdpEngineObjects struct {
	XdpEnginePrograms
	XdpEngineMaps
	XdpEngineVariables
}

func (o *XdpEngineObjects) Close() error {
	return _XdpEngineClose(
		&o.XdpEnginePrograms,
		&o.XdpEngineMaps,
	)
}

// XdpEngineMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadXdpEngineObjects or ebpf.CollectionSpec.LoadAndAssign.
type XdpEngineMaps struct {
	CmdQueue *ebpf.Map `ebpf:"cmd_queue"`
}

func (m *XdpEngineMaps) Close() error {
	return _XdpEngineClose(
		m.CmdQueue,
	)
}

// XdpEngineVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadXdpEngineObjects or ebpf.CollectionSpec.LoadAndAssign.
type XdpEngineVariables struct {
}

// XdpEnginePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadXdpEngineObjects or ebpf.CollectionSpec.LoadAndAssign.
type XdpEnginePrograms struct {
	XdpEngine *ebpf.Program `ebpf:"xdp_engine"`
}

func (p *XdpEnginePrograms) Close() error {
	return _XdpEngineClose(
		p.XdpEngine,
	)
}

func _XdpEngineClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed xdpengine_bpfeb.o
var _XdpEngineBytes []byte
